### ISSUE TITLE
I think this link is broken

### ISSUE THREAD

**Issue by Blaqmac** [rangle/radius#65]
The link for more information "https://radius-de.netlify.app/" provided on the Figma file seems to have broken. Please can you help fix it? Thanks for giving us Radius

**Comment by winkerVSbecks** [comment]
Thanks, the correct link is http://radius-ds.netlify.com/

**Comment by winkerVSbecks** [comment]
@Blaqmac which part of the file did you spot this in?

**Comment by Blaqmac** [comment]
It is my pleasure. I spotted it on the **Get Started with Radius** page of the Figma file shared on the community
