### ISSUE TITLE
Premature concrete implementation of aria-label

### ISSUE THREAD

**Issue by t-schemmer** [rangle/radius#73]
https://github.com/rangle/radius/blob/fd3ecf48f7f503b0341324928cc09f87fabdadb4/packages/ds/src/components/button/button.tsx#L172

Adding `aria-label` here to define the loading text might be premature, IMO.  It does not take in to account the possibilities of allowing a dev to change this labeling in further implementations of the component;  Consider `i18n` or `L10n`.

**Comment by winkerVSbecks** [comment]
Would something like this work?

```js
  <StyledButton {...(isLoading ? { 'aria-label': 'loading' } : {})} {...props}> ... </StyledButton>
```
That way, if the user sets an `aria-label` then it would override the default one. 

Alternatively, something like:

```js
({ loadingLabel = 'loading', ...props }) => (
  <StyledButton {...(isLoading ? { 'aria-label': loadingLabel } : {})}> ... </StyledButton>
)
```

**Comment by t-schemmer** [comment]
@winkerVSbecks

These mechanisms work, however, it might be best to leave these assumptions to the implementing developer.

I'm not sure adding `aria-label`  at this level  is the correct solution.  It seems very confining and strict, not allowing a developer to make the decision on how to apply this labeling (if needed at all).  i.e. do they want to use `aria-label`; `aria-labelledby`; `aria-describedby`; Changing the `label` prop itself (to be visibly shown) or using all these options together.

**Comment by winkerVSbecks** [comment]
I see, that makes sense. Would you be up for submitting a PR? We can remove the label entirely and add a section on how you can provide that accessibility label on the docs page?
